AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: Motadata-log-Group
Outputs:
  LogGroupARN:
    Description: ARN of the created CloudWatch Log Group
    Value: !GetAtt LogGroupName.Arn
