AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a CloudTrail trail and send logs to CloudWatch

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-cloudtrail-bucket-pmg
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
                Rules:
                - ObjectOwnership: ObjectWriter

  CloudTrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${CloudTrailBucket}/*'

  CloudTrailTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: MyCloudTrail-pmg
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: my-cloudtrail-bucket-pmg
      S3KeyPrefix: CloudTrailLogs/
      EnableLogFileValidation: true
      KMSKeyId: arn:aws:kms:ap-south-1:${subscription_id:key/69d028e7-b809-46d7-9a4f-fdd3700c66c8
      IncludeGlobalServiceEvents: true

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: MyCloudTrailLogs-pmg

  CloudTrailToCloudWatch:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref CloudWatchLogsGroup
      DestinationArn: !GetAtt CloudTrailTrail.CloudWatchLogsLogGroupArn
