Parameters:
  TrailName:
    Type: String
    Default: "Cloudformation-Trail"
  BucketName:
    Type: String
    Default: "pmg-firehose"
  LogGroupName:
    Type: String
    Default: "Motadata-log-Group"
  CloudWatchLogsRoleName:
    Type: String
    Default: "CloudTrailRoleForCloudWatchLogs_pmg"
# Conditions:
#   IsOrganizationsSupported:
#     Fn::Equals:
#       - { Ref: "AWS::Partition" }
#       - "aws"
Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupName

  CloudTrailLogsRole: # A role for your trail
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
        Version: '2012-10-17'
        RoleName: !Ref CloudWatchLogsRoleName

  CloudTrailLogsPolicy: # The policy for your role
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - 'logs:PutLogEvents'
          - 'logs:CreateLogStream'
          Effect: Allow
          Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}:*
        Version: '2012-10-17'
      PolicyName: DefaultPolicy
      Roles:
      - Ref: CloudTrailLogsRole

  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref BucketName
      S3KeyPrefix: "Motadata"
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
        - MyLogGroup
        - Arn
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
        - CloudWatchLogsRole
        - Arn
      # KMSKeyId:
      #   Fn::ImportValue: TrailKeyTest
      # Tags:
      #   - Key: "TagKeyIntTest"
      #     Value: "TagValueIntTest"
      #   - Key: "TagKeyIntTest2"
      #     Value: "TagValueIntTest2"
      # SnsTopicName:
      #   Fn::ImportValue: TrailTopicTest
      EventSelectors:
        - DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub "arn:${AWS::Partition}:s3"
          IncludeManagementEvents: true
          ReadWriteType: All

# Outputs:
#   MotadataLogGroupArn:
#     Description: CloudWatch Logs Log Group ARN
#     Value:
#       Fn::GetAtt:
#         - !Ref LogGroupName
#         - Arn
#     Export:
#       Name: !Ref LogGroupName
# # Outputs:
#   ARN:
#     Description: The trail ARN
#     Value:
#       'Fn::GetAtt':
#         - Trail
#         - Arn
#   TopicArn:
#     Description: The SnS Topic ARN
#     Value:
#       'Fn::GetAtt':
#         - Trail
#         - SnsTopicArn