AWSTemplateFormatVersion: '2010-09-09'
Description: Create CloudTrail Trail with CloudWatch Logs

Parameters:
  TrailName:
    Type: String
    Default: MyCloudTrail
  S3BucketName:
    Type: String
    Default: pmg-trail
  LogGroupName:
    Type: String
    Default: MyCloudTrailLogGroup

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: S3Bucket
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudTrailToPutLogs
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource:
              Fn::Sub: arn:aws:s3:::${S3BucketName}/AWSLogs/${AWS::AccountId}/*

  CloudTrail:
    Type: 'AWS::CloudTrail::Trail'
    DependsOn: S3BucketPolicy
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref S3BucketName
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      CloudWatchLogsLogGroupArn: !GetAtt CloudWatchLogsLogGroup.Arn

  CloudWatchLogsLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DependsOn: S3BucketPolicy
    Properties:
      LogGroupName: !Ref LogGroupName

Outputs:
  CloudTrailArn:
    Description: CloudTrail ARN
    Value: !GetAtt CloudTrail.Arn
