AWSTemplateFormatVersion: "2010-09-09"  #Creating role for cloudtrailS3 
Parameters:
  TrailName:
    Type: String
    Default: cloudformation-trail #To be added in parameter file

#role for cloudtrail and s3
Resources:
  CloudTrails3Role:
    Type: 'AWS::IAM::Role'
    # DeletionPolicy: Delete
    Properties:
      #RoleName: motadataCloudTrailRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudFormationCloudTrailS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                - 's3:PutObject'
                - 's3:GetObject'
                Resource: 
                  S3Storage: 'arn:aws:s3:::code-pmg' #!ImportValue S3ForTrailStack2-Storage  #parameterTOBECHANGED* 'arn:aws:s3:::cf-code-pmg'
