AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  TrailName:
    Type: String
    Default: cloudformation-trail
  S3BucketName:
    Type: String
    Default: new-pmg
  S3BucketPolicyName:
    Type: String
    Default: CloudTrailS3BucketPolicy

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: S3Bucket
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${S3BucketName}"

          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/cloudtrail-logs/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn:  S3BucketPolicy
    Properties:
      S3BucketName: !Ref S3BucketName
      S3KeyPrefix: cloudtrail-logs/
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true

  

Outputs:
  CloudTrailArn:
    Description: CloudTrail ARN
    Value: !GetAtt CloudTrail.Arn
